Repository digdir/digdir-camp-2025-desKI, pull requests merged in 2025-07, with the labels that each got.

#81 77 enhancement improving program speed
  .env.template
  .gitignore
  README.md
  app/api/chatbot.py
  app/config.py
  app/db/chroma_db/1d78db2e-f45e-4465-9fe0-eb43c66288ec/data_level0.bin
  app/db/chroma_db/1d78db2e-f45e-4465-9fe0-eb43c66288ec/length.bin
  app/dependencies/services.py
  app/main.py
  app/services/llm_service.py
  app/services/query_service.py
  db/chroma_db/chroma.sqlite3
  pyproject.toml
Labels: enhancement

#94 93 bug resend on timeout
  app/services/llm_service.py
  app/services/query_service.py
  app/utils/prompt_factory.py
Labels: bug

#103 Added log support, and fixed servicedesk
  app/api/servicedesk.py
  app/models/request_models.py
  app/services/llm_service.py
  app/services/query_service.py
  app/utils/prompt_factory.py
Labels: feature

#105 fixed bug
  app/models/request_models.py
Labels: bug

#107 Bug unprocessable entity
  app/models/request_models.py
  app/models/response_models.py
  app/utils/desensitize.py
Labels: bug

#109 104 support for brukerstotte fine tuned model
  app/config.py
  app/db/chroma_db/chroma.sqlite3
  app/dependencies/services.py
  app/services/llm_service.py
Labels: feature
